function enterInfo() {

    let name = document.getElementById('enterName').value;
    let number = document.getElementById('enterNumber').value;
    let dept = document.getElementById("enterDep").value;
    let code = document.getElementById("empCode").value;
    let hours = parseInt(document.getElementById("enterHrsWork").value);
    // let qlfCode = document.getElementById("radioBtn").value
    // let master = document.getElementById("clickM").value
    // let bachelor = document.getElementById("clickB").value
    // let qlfCode

    // let faculty = window.prompt("Enter the Qualification Code");
    // let regular = window.prompt("Enter the amount of monthly fixed salary");
    let fixSal;
    let perHour;
    let grosSal;
    let incomeTax;
    let netPay;
    let healthFee;
    let overTime;

    //'faculty'
    if (code == "F" || code == "f") {
        let qlfCode = window.prompt("Enter the Qualification Code");
        if (qlfCode == "M" || qlfcode == "m") {
            allowance = 1500;
            grosSal = hours * 175 + allowance; //faculty gross salaries are generated by the number of hours worked for a given month multiplied by their rate of pay plus a teaching allowance
        } else if (qlfCode == "B" || qlfcode == "b") {
            allowance = 600;
            grosSal = hours * 100 + allowance;
        } getDeduction();
    }
    //'regular'
    else if (code == "R" || code == "r") {
        let regular = window.prompt("Enter the amount of monthly fixed salary");
        fixSal = regular;
        perHour = fixSal / 160; //To get the employee hourly rate your program would have to divide the fixed salary by 160
        if (hours == 160) {
            grosSal = fixSal;   //if a Regular worker works 160 hours for the month then they would be paid flat fixed salary
        } else if (hours < 160) { //prorated = (fixSal / 160) * hours
            grosSal = perHour * hours;
        } else  { //over time = ((fixedSalary/160)*hours)*(hours-160)*2
            overTime = hours - 160;
            grosSal = overTime * (perHour * 2) + (perHour * 160);
        }
        getDeduction(); 
    }


    function getDeduction() { //If an employee earns more than $3000.00
        if (grosSal > 3000) {
            incomeTax = (grosSal - 2500) * 0.25;
            healthFee = 33; //per month then their health surcharge fee would be  $33.00.
            netPay = grosSal - (incomeTax + healthFee);
        } else if (grosSal <=3000) { //If an employee earns $3000.00 or less than
            incomeTax = (grosSal - 2500) * 0.25;
            healthFee = 19.20; //then their health surcharge fee would be $19.20.
            netPay = (incomeTax + healthFee) - grosSal;
         } else if (grosSal <= 2500) {
            incomeTax = "Tax Free"
            healthFee = 19.20;
            netPay = grosSal - healthFee;
         }
        paySlip();

    }

    function paySlip() {

        document.getElementById("generatedName").value = name;
        document.getElementById("generatedNumber").value = number;
        document.getElementById("generatedCode").value = code;
        document.getElementById("generatedDep").value = dept;
        document.getElementById("generatedHrs").value = hours;
        document.getElementById("generatedGrosSal").value = "$ " + grosSal;
        document.getElementById("generatedIncomeTax").value = "$ " + incomeTax;
        document.getElementById("generatedHealthFee").value = "$ " + healthFee;
        document.getElementById("generatedTotalSal").value = "$ " + netPay;

    }

}


let btn = document.getElementById("check");
btn.addEventListener("click", enterInfo);